version: '3'

services:
    
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:3000"
    links:
      - database
    depends_on:
      - database
    restart: always
    command: npm start


  database:
    container_name: database
    build: ./sql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "3005:80"
    depends_on:
      - database
    restart: always
    container_name: phpmyadmin
