version: '3'

services:
    
  server:
    container_name: server
    image: nodejs-server
    build: ./server
    ports:
      - "8080:8080"
    links:
      - database
    depends_on:
      - database
    restart: always
    command: nodemon index.js

  database:
    container_name: database
    image: mysql-database
    build: ./sql
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    restart: always

  phpmyadmin:
    image: php-myadmin
    build: ./phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD} 
    ports:
      - "3005:8080"
    depends_on:
      - database
    restart: always

  swagger:
    build: ./server/swagger
    environment:
      URL: /api/swagger.yaml
    ports:
      - "8081:8080"
    restart: always
    container_name: swagger
